# Generated by Django 2.2.4 on 2019-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movieid',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
